#%RAML 1.0 SecurityScheme
type: Basic Authentication
description: authenticating the user with client id and secret
describedBy:
  headers:
    clientId:
      type: string
    clientsecret:
      type: string